version: '3'

services:
  db:
    image: postgres:9.6.8
    ports:
      - "5432:5432"
    volumes:
      - appswingers_db_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: .
    image: appswingers_backend
    command: ["./wait-for-it.sh", "db:5432", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    restart: on-failure
    env_file: .env
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
  celery:
    image: appswingers_backend
    command: ./wait-for-it.sh rabbit:5672 -- sh run-celery.sh
    volumes:
      - .:/code
    restart: always
    depends_on:
      - rabbit

volumes:
  appswingers_db_data:
    external: true
