version: '3'

services:
  db:
    image: postgres:9.6.8
    ports:
      - "5432:5432"
    volumes:
      - appswingers_db_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    restart: on-failure
    env_file: .env

volumes:
  appswingers_db_data:
    external: true
